#项目启动的端口
server:
  address: 0.0.0.0:2022
  model: debug

#数据库配置
db:
  dialects: mysql
  host: 192.168.102.20
  port: 3306
  db: admin-go-api
  username: root
  password: 123456
  charset: utf8mb4
  #最大空闲连接数
  maxIdle: 10
  #最大连接数
  maxOpen: 100

#redis配置
redis:
  address: 192.168.102.20:6379
  password: 123456

#图片上传配置
imageSettings:
  #本地磁盘
  uploadDir: /admin-api/upload/
  #本地ip地址（线上地址可以更换）
  imageHost: http://localhost:2000